"""add date filter settings to topic_subscriptions

Revision ID: 20260308_0009_add_date_filter_settings
Revises: 20260228_0008_agent_conversations
Create Date: 2026-03-08

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "20260308_0009_add_date_filter_settings"
down_revision: str | None = "20260228_0008"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "topic_subscriptions",
        sa.Column("enable_date_filter", sa.Boolean(), nullable=False, server_default="false"),
    )
    op.add_column(
        "topic_subscriptions",
        sa.Column("date_filter_days", sa.Integer(), nullable=False, server_default="7"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("topic_subscriptions", "date_filter_days")
    op.drop_column("topic_subscriptions", "enable_date_filter")
    # ### end Alembic commands ###
