"""add date filter settings to topic_subscriptions

Revision ID: 20260308_0009_add_date_filter_settings
Revises: 20260228_0008_agent_conversations
Create Date: 2026-03-08

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "20260308_0009_add_date_filter_settings"
down_revision: Union[str, None] = "20260228_0008"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "topic_subscriptions",
        sa.Column("enable_date_filter", sa.Boolean(), nullable=False, server_default="false"),
    )
    op.add_column(
        "topic_subscriptions",
        sa.Column("date_filter_days", sa.Integer(), nullable=False, server_default="7"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("topic_subscriptions", "date_filter_days")
    op.drop_column("topic_subscriptions", "enable_date_filter")
    # ### end Alembic commands ###
